/**
 * Mutation Types
 *
 * This file contains a global list of all of the different
 * types of mutations that can be made to our Vuex store.
 */

/**
 * Authentication
 */
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const REFRESH_REQUEST = 'REFRESH_REQUEST'
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const REFRESH_FAILURE = 'REFRESH_FAILURE'
export const GOOGLE_TOKEN_REQUEST = 'GOOGLE_TOKEN_REQUEST'
export const GOOGLE_TOKEN_SUCCESS = 'GOOGLE_TOKEN_SUCCESS'
export const GOOGLE_TOKEN_FAILURE = 'GOOGLE_TOKEN_FAILURE'
export const LOGOUT = 'LOGOUT'

/**
 * User profile management
 */
export const SET_API_USER_ID = 'SET_API_USER_ID'
export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAILURE = 'PROFILE_FAILURE'
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'

/**
 * Artifacts
 */
// synchronous
export const REMOVE_ARTIFACT = 'REMOVE_ARTIFACT'
export const SAVE_ARTIFACT = 'SAVE_ARTIFACT'
// asynchronous
export const CREATE_ARTIFACT_REQUEST = 'CREATE_ARTIFACT_REQUEST'
export const CREATE_ARTIFACT_SUCCESS = 'CREATE_ARTIFACT_SUCCESS'
export const CREATE_ARTIFACT_FAILURE = 'CREATE_ARTIFACT_FAILURE'
export const UPDATE_ARTIFACT_REQUEST = 'UPDATE_ARTIFACT_REQUEST'
export const UPDATE_ARTIFACT_SUCCESS = 'UPDATE_ARTIFACT_SUCCESS'
export const UPDATE_ARTIFACT_FAILURE = 'UPDATE_ARTIFACT_FAILURE'
export const SYNC_ARTIFACTS_REQUEST = 'SYNC_ARTIFACTS_REQUEST'
export const SYNC_ARTIFACTS_SUCCESS = 'SYNC_ARTIFACTS_SUCCESS'
export const SYNC_ARTIFACTS_FAILURE = 'SYNC_ARTIFACTS_FAILURE'
export const LOAD_ARTIFACTS_REQUEST = 'LOAD_ARTIFACTS_REQUEST'
export const LOAD_ARTIFACTS_SUCCESS = 'LOAD_ARTIFACTS_SUCCESS'
export const LOAD_ARTIFACTS_FAILURE = 'LOAD_ARTIFACTS_FAILURE'
export const DELETE_ARTIFACT_REQUEST = 'DELETE_ARTIFACT_REQUEST'
export const DELETE_ARTIFACT_SUCCESS = 'DELETE_ARTIFACT_SUCCESS'
export const DELETE_ARTIFACT_FAILURE = 'DELETE_ARTIFACT_FAILURE'
export const SET_SEARCH_TERMS = 'SET_SEARCH_TERMS'
export const SET_STATUSES = 'SET_STATUSES'

/**
 * Common module
 */
export const ADD_ERROR_TO_QUEUE = 'ADD_ERROR_TO_QUEUE'
export const ADD_ITEM_TO_QUEUE = 'ADD_ITEM_TO_QUEUE'
export const PAUSE_QUEUE = 'PAUSE_QUEUE'
export const REMOVE_ITEM_FROM_QUEUE = 'REMOVE_ITEM_FROM_QUEUE'
export const RESUME_QUEUE = 'RESUME_QUEUE'
export const SET_ONLINE_STATUS = 'SET_ONLINE_STATUS'
export const TOGGLE_NAV_DRAWER_MINI = 'TOGGLE_NAV_DRAWER_MINI'
